# Generated by Django 5.1.3 on 2026-05-02 18:34

import apps.core.utils
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(default=apps.core.utils.generate_order_number, max_length=32, unique=True)),
                ('email_snapshot', models.EmailField(help_text='buyer email at the time of order', max_length=254)),
                ('phone_snapshot', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=64)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('payment_provider', models.CharField(blank=True, max_length=32)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('notes_internal', models.TextField(blank=True)),
                ('notes_customer', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'orders_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sku', models.CharField(max_length=64)),
                ('name_snapshot', models.CharField(max_length=255)),
                ('attributes_snapshot', models.JSONField(blank=True, default=dict)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'orders_item',
            },
        ),
    ]
