apiVersion: v1
kind: ConfigMap
metadata:
  name: novacommerce-config
  namespace: novacommerce
data:
  ENV: "prod"
  DEBUG: "false"
  ALLOWED_HOSTS: "novacommerce.example.com,fastapi.novacommerce.example.com"
  DJANGO_SETTINGS_MODULE: "novacommerce.settings.prod"
  CSRF_TRUSTED_ORIGINS: "https://novacommerce.example.com"
  CORS_ALLOWED_ORIGINS: "https://novacommerce.example.com"
  LOG_FORMAT: "json"
  LOG_LEVEL: "INFO"
