# Generated by Django 5.1.3 on 2026-05-02 18:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day', models.DateField(db_index=True, unique=True)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('paid_orders_count', models.PositiveIntegerField(default=0)),
                ('cancelled_orders_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_sold', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_daily_sales',
                'ordering': ['-day'],
            },
        ),
    ]
