# Generated by Django 5.1.3 on 2026-05-02 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('eta_days_min', models.PositiveIntegerField(default=1)),
                ('eta_days_max', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('flat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'shipping_method',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('courier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], db_index=True, default='preparing', max_length=24)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.shippingmethod')),
            ],
            options={
                'db_table': 'shipping_shipment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='shipping_sh_order_i_a287c9_idx')],
            },
        ),
    ]
