# Generated by Django 5.1.3 on 2026-05-02 18:34

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('percent', 'Percent off'), ('fixed', 'Fixed amount off'), ('free_shipping', 'Free shipping')], default='percent', max_length=24)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent (0-100) or fixed currency amount.', max_digits=12)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage discounts.', max_digits=12, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'coupons_coupon',
                'ordering': ['-created_at'],
            },
        ),
    ]
